## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-
def build(bld):
    obj = bld.create_ns3_program('large-scale-sim',
                                 ['point-to-point', 'applications', 'internet', 'flow-monitor'])
    obj.source = ['large-scale-sim.cc', 'cdf.c']
